import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-crop-insurance-claim-recovery",
  "engine": "recovery",
  "title": "Crop Insurance Claim Recovery",
  "shortTitle": "Crop Insurance Claim Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through crop insurance claim recovery",
  "industry": "Agricultural Insurance Recovery",
  "uiPort": 4638,
  "apiPort": 5638,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Crop Insurance Claim Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidIndemnity",
    "expectedKey": "eligibleIndemnity",
    "actualLabel": "Paid Crop Indemnity",
    "expectedLabel": "Calculated Eligible Indemnity",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Crop Insurance Claim Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("farm-unit-acreage-registry","CIC01","Farm unit acreage registry","Execute farm unit acreage registry using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed farm unit acreage registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Farm unit acreage registry Reference","text","CIC01-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("policy-endorsement-library","CIC02","Policy endorsement library","Execute policy endorsement library using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed policy endorsement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Policy endorsement library Reference","text","CIC02-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("acreage-report-reconciliation","CIC03","Acreage report reconciliation","Execute acreage report reconciliation using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed acreage report reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Acreage report reconciliation Reference","text","CIC03-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("production-history","CIC04","Production history","Execute production history using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed production history decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Production history Reference","text","CIC04-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("harvest-scale-ticket-ingestion","CIC05","Harvest scale-ticket ingestion","Execute harvest scale-ticket ingestion using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed harvest scale-ticket ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Harvest scale-ticket ingestion Reference","text","CIC05-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("yield-loss-calculation","CIC06","Yield loss calculation","Execute yield loss calculation using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed yield loss calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Yield loss calculation Reference","text","CIC06-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("revenue-protection-calculation","CIC07","Revenue protection calculation","Execute revenue protection calculation using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed revenue protection calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Revenue protection calculation Reference","text","CIC07-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("harvest-price-validation","CIC08","Harvest price validation","Execute harvest price validation using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed harvest price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Harvest price validation Reference","text","CIC08-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("prevented-planting-eligibility","CIC09","Prevented planting eligibility","Execute prevented planting eligibility using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed prevented planting eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Prevented planting eligibility Reference","text","CIC09-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("replant-payment-calculation","CIC10","Replant payment calculation","Execute replant payment calculation using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed replant payment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Replant payment calculation Reference","text","CIC10-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("quality-adjustment","CIC11","Quality adjustment","Execute quality adjustment using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed quality adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Quality adjustment Reference","text","CIC11-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("notice-of-loss-deadline","CIC12","Notice-of-loss deadline","Execute notice-of-loss deadline using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed notice-of-loss deadline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Notice-of-loss deadline Reference","text","CIC12-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("adjuster-evidence-package","CIC13","Adjuster evidence package","Execute adjuster evidence package using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed adjuster evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Adjuster evidence package Reference","text","CIC13-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("indemnity-reconciliation","CIC14","Indemnity reconciliation","Execute indemnity reconciliation using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed indemnity reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Indemnity reconciliation Reference","text","CIC14-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]}),
feature("crop-county-peril-analytics","CIC15","Crop county peril analytics","Execute crop county peril analytics using farms, units, acreage, policies, endorsements, production history, harvest records, scale tickets, yields, prices, prevented planting, replanting, quality, notices, and indemnities.","Produce a governed crop county peril analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Producer / Crop Policy","text","Producer / Crop Policy · Standard Case"],["caseReference","Crop county peril analytics Reference","text","CIC15-2026-001"],["paidIndemnity","Paid Crop Indemnity","currency",1289500],["eligibleIndemnity","Calculated Eligible Indemnity","currency",1521610],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidIndemnity",subjects:["Farm unit acreage registry case","Policy endorsement library case","Acreage report reconciliation case","Production history case","Harvest scale-ticket ingestion case"]})
]);
